name: xcos_template
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.1=py38_0
  - astroid=2.3.3=py38_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py38_0
  - bcolz=1.2.1=py38h962f231_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - blosc=1.16.3=hd408876_0
  - bokeh=1.4.0=py38_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - click=7.0=py_0
  - cloudpickle=1.2.2=py_1
  - coloredlogs=10.0=py38_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py38h516909a_0
  - dask=2.10.1=py_0
  - dask-core=2.10.1=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.10.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.6=he6710b0_0
  - flake8=3.7.9=py38_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fsspec=0.6.2=py_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - grpcio=1.16.1=py38hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - humanfriendly=4.18=py38_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.6.1=py38_0
  - importlib_metadata=1.5.0=py38_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py38_0
  - jedi=0.16.0=py38_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=5.3.4=py38_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py38_0
  - kiwisolver=1.1.0=py38hc9558a2_0
  - lazy-object-proxy=1.4.3=py38h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - locket=0.2.0=py38_1
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - markdown=3.1.1=py38_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.0=166
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - mock=4.0.1=py_0
  - msgpack-python=0.6.1=py38hfd86e86_1
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - ninja=1.9.0=py38hfd86e86_0
  - notebook=6.0.3=py38_0
  - numexpr=2.7.1=py38h423224d_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1d=h7b6447c_4
  - packaging=20.1=py_0
  - pandas=1.0.0=py38h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.6.1=py_0
  - partd=1.1.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.0.0=py38hb39fc2d_0
  - pip=20.0.2=py38_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.2=py38he6710b0_0
  - psutil=5.6.7=py38h7b6447c_0
  - ptyprocess=0.6.0=py38_0
  - pycodestyle=2.5.0=py38_0
  - pyflakes=2.1.1=py38_0
  - pygments=2.5.2=py_0
  - pylint=2.4.4=py38_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.15.7=py38h7b6447c_0
  - pytables=3.6.1=py38h9fd0a39_0
  - python=3.8.1=h0371630_1
  - python-dateutil=2.8.1=py_0
  - pytorch=1.4.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py38hc1659b7_0
  - pyyaml=5.3=py38h7b6447c_0
  - pyzmq=18.1.1=py38he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.6.0=py_1
  - readline=7.0=h7b6447c_5
  - rope=0.16.0=py_0
  - scikit-image=0.16.2=py38hb3f55d8_0
  - scikit-learn=0.22.1=py38hd81dba3_0
  - scipy=1.4.1=py38h0b6359f_0
  - send2trash=1.5.0=py38_0
  - setuptools=45.1.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.14.0=py38_0
  - snappy=1.1.7=hbae5bb6_3
  - sortedcontainers=2.1.0=py38_0
  - sqlite=3.31.1=h7b6447c_0
  - tblib=1.6.0=py_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py38_cu101
  - tornado=6.0.3=py38h7b6447c_3
  - traitlets=4.3.3=py38_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.11.2=py38h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=1.0.0=py_0
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - appdirs==1.4.3
    - attrdict==2.0.1
    - black==19.10b0
    - opencv-contrib-python==4.2.0.32
    - pathspec==0.7.0
    - regex==2020.1.8
    - tensorboardx==2.0
    - toml==0.10.0
    - typed-ast==1.4.1
prefix: /home/r07944011/anaconda3/envs/xcos_template

