name: PytorchGoldenTemplate
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - attrdict=2.0.1=py_0
  - audioread=2.1.6=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - cairo=1.14.12=h80bd089_1005
  - certifi=2019.6.16=py37_1
  - cffi=1.11.5=py37he75722e_1
  - cloudpickle=0.7.0=py_0
  - coloredlogs=10.0=py37_1000
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py37h14c3975_1
  - dask-core=1.1.1=py_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.2=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.5=hf484d3e_1002
  - ffmpeg=4.0.2=ha0c5888_2
  - flake8=3.7.7=py37_0
  - fontconfig=2.13.1=h2176d3f_1000
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.9.1=h8a8886c_1
  - gettext=0.19.8.1=h9745a5d_1001
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.9.0=he243708_1001
  - hdf5=1.10.2=hc401514_3
  - humanfriendly=4.17=py37_1000
  - icu=58.2=hf484d3e_1000
  - imageio=2.4.1=py37_0
  - intel-openmp=2019.1=144
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.13.2=py37_0
  - joblib=0.13.2=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py37h6bb024c_1002
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libflac=1.3.1=hf484d3e_1002
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1000
  - libiconv=1.15=h14c3975_1004
  - libogg=1.3.2=h14c3975_1001
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hdbcaa40_1000
  - librosa=0.7.0=py_0
  - libsndfile=1.0.28=hf484d3e_1000
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=2.32.1=h14c3975_1000
  - libvorbis=1.3.5=h14c3975_1001
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - llvmlite=0.29.0=py37hfd453ef_1
  - matplotlib=3.0.2=py37_1002
  - matplotlib-base=3.0.2=py37h167e16e_1002
  - mccabe=0.6.1=py37_1
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.3=0
  - networkx=2.2=py37_1
  - ninja=1.8.2=py37h6bb024c_1
  - numba=0.44.1=py37hb3f55d8_0
  - numpy=1.15.4=py37h7e9f1db_0
  - numpy-base=1.15.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1c=h516909a_0
  - pandas=0.24.1=py37he6710b0_0
  - parso=0.3.2=py37_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.4.1=py37h34e0f95_0
  - pip=19.0.1=py37_0
  - pixman=0.34.0=h14c3975_1003
  - prompt_toolkit=2.0.8=py_0
  - protobuf=3.6.1=py37hf484d3e_1001
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.3.1=py37_0
  - pyparsing=2.3.1=py_0
  - pyqt=5.6.0=py37h13b7fb3_1008
  - pysoundfile=0.10.2=py_1001
  - python=3.7.1=h0371630_7
  - python-dateutil=2.7.5=py37_0
  - pytorch=1.0.0=py3.7_cuda9.0.176_cudnn7.4.1_1
  - pytz=2018.9=py37_0
  - pywavelets=1.0.1=py37hdd07704_0
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - resampy=0.2.1=py_1
  - scikit-image=0.14.1=py37he6710b0_0
  - scikit-learn=0.20.3=py37hd81dba3_0
  - scipy=1.2.0=py37h7c811a0_0
  - setuptools=40.7.3=py37_0
  - sip=4.18.1=py37hf484d3e_1000
  - six=1.12.0=py37_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.9=h84994c4_1000
  - toolz=0.9.0=py37_0
  - torchvision=0.2.1=py_2
  - tornado=5.1.1=py37h14c3975_1000
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.32.3=py37_0
  - x264=1!152.20180717=h14c3975_1001
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h14c3975_1004
  - xorg-libsm=1.2.3=h4937e3b_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - xorg-libxext=1.3.3=h14c3975_1004
  - xorg-libxfixes=5.0.3=h14c3975_1004
  - xorg-libxi=1.7.9=h14c3975_1002
  - xorg-libxrender=0.9.10=h14c3975_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - tensorboardx==1.8
prefix: /home/yaliangchang/miniconda3/envs/PytorchGoldenTemplate

